name: Construir y Publicar Imagen Docker

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # Descargar el repo
      - name: Descargar repositorio
        uses: actions/checkout@v3

      # Configurar QEMU para builds multiplataforma (opcional pero recomendado)
      - name: Configurar QEMU
        uses: docker/setup-qemu-action@v3

      # Configurar Buildx (para mejor caching y multiplataforma)
      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Login a DockerHub
      - name: Iniciar sesión en DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construir y subir imagen
      - name: Construir y Publicar Imagen Docker
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ${{ secrets.DOCKER_USER }}/front_web:latest
            ${{ secrets.DOCKER_USER }}/front_web:${{ github.sha }}
